## Importing Library

In [2]:
import pandas as pd
import numpy as np
import csv

In [3]:
!pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 25.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=964d9d5397c4ac0dd94f2d2ee2be93c5dc7c0504604465ec36154a1cde183539
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

## User Data Loading

In [4]:
#mount drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#loading user csv data
user_data_file_path = "/content/drive/MyDrive/Companies Interview Projects/InShorts/data/devices/part-00000-cdb2cdd7-9d14-4000-b947-4d0475444217-c000.csv"

df_user = pd.read_csv(user_data_file_path)

#preview the head data
df_user.head(5)

,deviceid,platform,os_version,model,networkType,district,lastknownsubadminarea,language_selected,created_datetime,app_updated_at,last_active_at
0,197b123e-eb9e-4fc1-a32d-aa86aaea425e,ANDROID,13,NaN,4G,NaN,NaN,en,2023-07-11T13:40:05.511Z,NaN,2023-07-11T13:40:02.000Z
1,3c33c537-7c6c-40f5-835c-f997e883cae2,ANDROID,13,NaN,4G,NaN,NaN,en,2023-07-11T15:36:58.363Z,NaN,2023-07-11T16:24:44.000Z
2,6c7be5d0-d4d8-469f-91be-8055021ceef9,ANDROID,12,NaN,NO INTERNET,NaN,NaN,en,2023-07-11T11:25:39.375Z,NaN,2023-07-11T10:13:18.000Z
3,0801af66-0a6f-4fdd-82a9-c2b15757b8f5,ANDROID,7.0,NaN,NO INTERNET,NaN,NaN,en,2023-04-30T00:24:48.987Z,NaN,2023-07-10T11:53:21.000Z
4,78b3c7a7-5881-42dc-9f8e-b4fc27f94360,ANDROID,13,NaN,4G,NaN,NaN,en,2023-04-15T05:48:46.923Z,NaN,2023-07-20T15:37:47.000Z

In [ ]:
#preview the tail data
df_user.tail(5)

,deviceid,platform,os_version,model,networkType,district,lastknownsubadminarea,language_selected,created_datetime,app_updated_at,last_active_at
10395,2f2c7f12-919e-4692-9cf2-e1ee90238958,ANDROID,12,Xiaomi POCO M2 Pro,4G,NaN,Lawar Khas,en,2023-04-26T07:01:25.537Z,NaN,2023-07-25T09:14:37.000Z
10396,3e78edec-c369-490b-8a12-35b00b8ece36,ANDROID,12,Motorola moto g62 5G,4G,NaN,Bengaluru,en,2023-05-05T11:23:11.527Z,2023-07-22,2023-07-25T09:14:01.000Z
10397,b2c0071d-2b86-41fc-b0e3-5689e9aedef1,ANDROID,10,Xiaomi Redmi 8A Dual,WIFI,NaN,Delhi,en,2023-04-16T04:12:36.767Z,NaN,2023-07-25T03:42:12.000Z
10398,0eaa96ab-7b42-446f-a877-60aaf70dc144,ANDROID,12,Infinix Infinix X6517,4G,NaN,Limburg an der Lahn,en,2023-05-04T00:22:45.911Z,2023-06-28,2023-07-25T16:11:49.000Z
10399,017120da-5a11-4139-a438-97906a941a46,ANDROID,12,Xiaomi Redmi Note 9 Pro Max,WIFI,NaN,Vadakku Valliyur,en,2023-05-08T03:30:09.838Z,2023-06-28,2023-07-25T16:28:25.000Z

## User Data Cleaning

In [ ]:
#check column data types
df_user.dtypes

deviceid                 object
platform                 object
os_version               object
model                    object
networkType              object
district                 object
lastknownsubadminarea    object
language_selected        object
created_datetime         object
app_updated_at           object
last_active_at           object
dtype: object

In [ ]:
#check cloumn info
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10400 entries, 0 to 10399
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   deviceid               10400 non-null  object
 1   platform               10400 non-null  object
 2   os_version             10400 non-null  object
 3   model                  10344 non-null  object
 4   networkType            10352 non-null  object
 5   district               21 non-null     object
 6   lastknownsubadminarea  9492 non-null   object
 7   language_selected      10400 non-null  object
 8   created_datetime       10400 non-null  object
 9   app_updated_at         7236 non-null   object
 10  last_active_at         10400 non-null  object
dtypes: object(11)
memory usage: 893.9+ KB

In [ ]:
#shape
df_user.shape

(10400, 11)

In [ ]:
#get summary statistics of columns
df_user.describe()

,deviceid,platform,os_version,model,networkType,district,lastknownsubadminarea,language_selected,created_datetime,app_updated_at,last_active_at
count,10400,10400,10400,10344,10352,21,9492,10400,10400,7236,10400
unique,10400,1,16,985,5,20,1157,1,10400,104,10330
top,d74d7a72-8d07-47af-a490-1b57f9280b54,ANDROID,13,Oneplus CPH2381,4G,MH_NG,Mumbai,en,2023-04-27T09:03:30.386Z,2023-06-30,2023-07-25T17:14:33.000Z
freq,1,10400,3816,182,6621,2,651,10400,1,488,3

In [ ]:
#check missing values
df_user.isnull().sum()

deviceid                     0
platform                     0
os_version                   0
model                       56
networkType                 48
district                 10379
lastknownsubadminarea      908
language_selected            0
created_datetime             0
app_updated_at            3164
last_active_at               0
dtype: int64

In [ ]:
# Frequency of unique values in a categorical column
print(df_user['model'].value_counts())

model
Oneplus CPH2381            182
Oneplus CPH2467            156
Xiaomi Redmi Note 7 Pro    112
Oneplus CPH2487            107
Samsung SM-M315F            93
                          ...
Asus ASUS_I003DD             1
Sony G8142                   1
Motorola moto e32(s)         1
Hmd Global Nokia 3.4         1
Samsung SM-S908N             1
Name: count, Length: 985, dtype: int64

In [ ]:
df_user['networkType'].value_counts()

networkType
4G             6621
WIFI           3489
NO INTERNET     172
3G               57
2G               13
Name: count, dtype: int64

In [ ]:
df_user['district'].value_counts()

district
MH_NG    2
DL_SH    1
CG_JC    1
UP_JP    1
MP_BL    1
HR_JH    1
UP_MB    1
UP_ET    1
TS_WP    1
MH_TH    1
DL_NW    1
RJ_AL    1
HR_JI    1
CG_BI    1
BR_BE    1
BR_NL    1
PB_AM    1
WB_PM    1
UP_MO    1
MH_WR    1
Name: count, dtype: int64

In [ ]:
df_user['lastknownsubadminarea'].value_counts()

lastknownsubadminarea
Mumbai         651
Delhi          374
Bengaluru      367
Noida          268
Gurgaon        250
              ...
Ko Pha Ngan      1
Orillia          1
Cupertino        1
Keelakarai       1
Munnar           1
Name: count, Length: 1157, dtype: int64

In [ ]:
#Identify row duplicates
print(df_user.duplicated().sum())

0

In [ ]:
#Remove duplicates
df_user = df_user.drop_duplicates()

In [ ]:
#removing duplicates deviceid
df_user = df_user.drop_duplicates(subset=['deviceid'])

In [ ]:
#dropping column model
df_user = df_user.drop(columns=['model','district','app_updated_at'])

In [ ]:
#setting null values to 4G in network type
df_user['networkType'] = df_user['networkType'].fillna('4G')

In [ ]:
#setting null values to Unknown_Location in lastknownsubdomainarea
df_user['lastknownsubadminarea'] = df_user['lastknownsubadminarea'].fillna('Unknown_Location')

In [ ]:
#check missing values
df_user.isnull().sum()

deviceid                 0
platform                 0
os_version               0
networkType              0
lastknownsubadminarea    0
language_selected        0
created_datetime         0
last_active_at           0
dtype: int64

In [ ]:
df_user.to_csv('/content/drive/MyDrive/Companies Interview Projects/InShorts/cleaned_data/user_cleaned_data.csv',index=False)

# Content Data Cleaning

In [ ]:
#loading user csv data

# Read CSV using the python engine with proper quoting
df_content = pd.read_csv(
    "/content/drive/MyDrive/Companies Interview Projects/InShorts/data/training_content/part-00000-a34a1545-5cf1-47b9-93c2-29c1d3f0bfb7-c000.csv",
    engine='python',        # python engine handles quotes and newlines better
    quoting=csv.QUOTE_ALL,  # treat text in quotes as one field
    quotechar='"',          # standard quote char
    escapechar='\\',        # handle escaped quotes
    on_bad_lines='warn'     # just warn for truly broken lines
)

#preview the head data
df_content.head(5)

,hashid,title,content,newsType,author,categories,hashtags,newsDistrict,createdAt,updatedAt,newsLanguage,sourceName
0,q6ymyudu-1,The world's most picturesque road trip awaits ...,The world's most picturesque road trip awaits ...,VIDEO_NEWS,5748e05c947ce445479635a0,travel,NaN,NaN,2023-06-04T08:30:15.000Z,2023-06-04T08:30:15.000Z,english,NaN
1,vowkjbc6-1,"In a viral video, Kathak dancers perform in a ...","In a viral video, Kathak dancers perform in a ...",VIDEO_NEWS,5748e05c947ce445479635a0,entertainment,NaN,NaN,2023-06-05T15:02:18.000Z,2023-06-05T15:02:18.000Z,english,NaN
2,8bf90wsx-1,Would you like to be a part of the 'no wash' m...,Would you like to be a part of the 'no wash' m...,VIDEO_NEWS,5748e05c947ce445479635a0,hatke,NaN,NaN,2023-06-02T09:22:13.000Z,2023-06-02T09:22:13.000Z,english,NaN
3,j0p0fukx-1,Switzerland's legendary Bernina Express turns 50,Switzerland's legendary Bernina Express turns 50,VIDEO_NEWS,5748e05c947ce445479635a0,travel,NaN,NaN,2023-06-04T13:24:40.000Z,2023-06-04T13:24:40.000Z,english,NaN
4,naqusao7-1,"Explored by many, claimed by none, this is Bir...","Explored by many, claimed by none, this is Bir...",VIDEO_NEWS,5748e05c947ce445479635a0,"hatke,travel",NaN,NaN,2023-06-04T13:20:20.000Z,2023-06-04T13:20:20.000Z,english,NaN

In [ ]:
df_content.columns

Index(['hashid', 'title', 'content', 'newsType', 'author', 'categories',
       'hashtags', 'newsDistrict', 'createdAt', 'updatedAt', 'newsLanguage',
       'sourceName'],
      dtype='object')

In [ ]:
df_content.dtypes

hashid          object
title           object
content         object
newsType        object
author          object
categories      object
hashtags        object
newsDistrict    object
createdAt       object
updatedAt       object
newsLanguage    object
sourceName      object
dtype: object

In [ ]:
df_content.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14621 entries, 0 to 14620
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   hashid        14621 non-null  object
 1   title         14621 non-null  object
 2   content       14621 non-null  object
 3   newsType      13978 non-null  object
 4   author        14619 non-null  object
 5   categories    14621 non-null  object
 6   hashtags      2779 non-null   object
 7   newsDistrict  20 non-null     object
 8   createdAt     14621 non-null  object
 9   updatedAt     14621 non-null  object
 10  newsLanguage  14509 non-null  object
 11  sourceName    14451 non-null  object
dtypes: object(12)
memory usage: 1.3+ MB

In [ ]:
df_content.shape

(14621, 12)

In [ ]:
df_content.describe()

,hashid,title,content,newsType,author,categories,hashtags,newsDistrict,createdAt,updatedAt,newsLanguage,sourceName
count,14621,14621,14621,13978,14619,14621,2779,20,14621,14621,14509,14451
unique,14621,12989,12994,2,149,191,150,2,12950,13153,3,342
top,1wr3xgtu-1,Stop & Spot,Stop & Spot,NEWS,5f70de9bd43821580e6d7022,national,NCPCrisis,BR_PA,2023-07-06T14:10:35.000Z,2023-07-24T06:52:44.000Z,english,YouTube
freq,1,14,14,13808,856,3443,210,17,4,3,12302,2693

In [ ]:
df_content.isnull().sum()

hashid              0
title               0
content             0
newsType          643
author              2
categories          0
hashtags        11842
newsDistrict    14601
createdAt           0
updatedAt           0
newsLanguage      112
sourceName        170
dtype: int64

In [ ]:
#removing the duplicates hashid
df_content.drop_duplicates(subset='hashid', inplace=True)

In [ ]:
df_content['newsType'].value_counts()

newsType
NEWS          13808
VIDEO_NEWS      170
Name: count, dtype: int64

In [ ]:
df_content['categories'].value_counts()

categories
national                                  3443
entertainment                             1959
world                                     1553
sports                                    1385
politics,national                          919
                                          ...
world,education,national                     1
experiment,entertainment                     1
politics,Union_Budget_2023-24,national       1
miscellaneous,world                          1
world,कोरोना_वायरस                           1
Name: count, Length: 191, dtype: int64

In [ ]:
df_content['hashtags'].value_counts()

hashtags
NCPCrisis                   210
Monsoons2023                182
GangrapesInManipur          165
WagnerVsRussianMilitary     143
ManipurViolence             137
                           ...
NehruMemorialRenamed          1
SengolInNewParliament         1
KingCharlesCoronation         1
IndiaMostPopulousInWorld      1
SidhuMoosewalaKilling         1
Name: count, Length: 150, dtype: int64

In [ ]:
df_content['newsDistrict'].value_counts()

newsDistrict
BR_PA    17
GJ_VD     3
Name: count, dtype: int64

In [ ]:
#analyzing content length for text news and video news
df_content['content_length'] = df_content['content'].apply(lambda x: len(str(x)))
text_news = df_content[df_content['newsType'] == 'NEWS']
video_news = df_content[df_content['newsType'] == 'VIDEO_NEWS']
print(text_news['content_length'].mean(), video_news['content_length'].mean())

347.969365585168 67.24705882352941

In [ ]:
#Filling News Type
def infer_news_type(row):
    text = str(row['content']).lower()
    if len(text.split()) < 70 or any(word in text for word in ['watch', 'video', 'clip', 'see']):
        return 'VIDEO_NEWS'
    elif str(row['categories']).lower() in ['entertainment', 'travel', 'hatke']:
        return 'VIDEO_NEWS'
    else:
        return 'NEWS'

df_content['newsType'] = df_content['newsType'].fillna('Unknown_Type')
mask_unknown = df_content['newsType'].isin(['Unknown_Type'])
df_content.loc[mask_unknown, 'newsType'] = df_content[mask_unknown].apply(infer_news_type, axis=1)

In [ ]:
#setting null values to Unknown_Author
df_content['author'] = df_content['author'].fillna('Unknown_Author')

In [ ]:
#setting source name to Unknown_Source
df_content['sourceName'] = df_content['sourceName'].fillna('Unknown_Source')

In [ ]:
df_content.isnull().sum()

hashid                0
title                 0
content               0
newsType              0
author                0
categories            0
hashtags          11842
newsDistrict      14601
createdAt             0
updatedAt             0
newsLanguage        112
sourceName            0
content_length        0
dtype: int64

In [ ]:
df_content = df_content.drop(columns=['newsDistrict'])

In [ ]:
df_content["newsLanguage"].value_counts()

newsLanguage
english     12302
hindi        2204
gujarati        3
Name: count, dtype: int64

In [ ]:
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0  # ensures consistent results

def detect_language_safe(text):
    """Detect language safely; return 'unknown' if detection fails."""
    try:
        return detect(str(text))
    except:
        return 'unknown'

In [ ]:
mask_missing_lang = df_content['newsLanguage'].isna() | (df_content['newsLanguage'] == '')

# Detect language for missing ones
df_content.loc[mask_missing_lang, 'detected_lang'] = df_content.loc[mask_missing_lang, 'content'].apply(detect_language_safe)

In [ ]:
df_content['detected_lang'].value_counts()

detected_lang
en    112
Name: count, dtype: int64

In [ ]:
df_content.loc[
    (mask_missing_lang) & (df_content['detected_lang'] == 'en'),
    'newsLanguage'
] = 'english'

df_content.loc[
    (mask_missing_lang) & (df_content['detected_lang'] != 'en'),
    'newsLanguage'
] = 'Unknown_Language'

In [ ]:
df_content['newsLanguage'].value_counts()

newsLanguage
english     12414
hindi        2204
gujarati        3
Name: count, dtype: int64

In [ ]:
df_content.drop(columns=['detected_lang'], inplace=True)

In [ ]:
df_content.isnull().sum()

hashid                0
title                 0
content               0
newsType              0
author                0
categories            0
hashtags          11842
createdAt             0
updatedAt             0
newsLanguage          0
sourceName            0
content_length        0
dtype: int64

In [ ]:
#Handling of hastag values
df_content['hashtags'] = df_content['hashtags'].fillna('')

df_content['hashtags'] = df_content['hashtags'].astype(str).str.replace('#', '', regex=False)
df_content['hashtags'] = df_content['hashtags'].str.replace(',', ' ', regex=False)
df_content['hashtags'] = df_content['hashtags'].str.replace('_', ' ', regex=False)

In [ ]:
df_content['title'] = ( df_content['title'].fillna('') + ' ' + df_content['hashtags'].fillna(''))
df_content.drop(columns=['hashtags'], inplace=True)

In [ ]:
df_content.isnull().sum()

hashid            0
title             0
content           0
newsType          0
author            0
categories        0
createdAt         0
updatedAt         0
newsLanguage      0
sourceName        0
content_length    0
dtype: int64

In [ ]:
df_content.to_csv('/content/drive/MyDrive/Companies Interview Projects/InShorts/cleaned_data/content_cleaned_data.csv', index=False)

## Interaction Data Loading

In [ ]:
#loading user csv data

# Read CSV using the python engine with proper quoting
df_interaction_1 = pd.read_csv("/content/drive/MyDrive/Companies Interview Projects/InShorts/data/event/part-00000-7e210b01-29d8-430f-988f-d3e3b34da614-c000.csv")
df_interaction_2 = pd.read_csv("/content/drive/MyDrive/Companies Interview Projects/InShorts/data/event/part-00001-7e210b01-29d8-430f-988f-d3e3b34da614-c000.csv")
df_interaction_3 = pd.read_csv("/content/drive/MyDrive/Companies Interview Projects/InShorts/data/event/part-00002-7e210b01-29d8-430f-988f-d3e3b34da614-c000.csv")
df_interaction_4 = pd.read_csv("/content/drive/MyDrive/Companies Interview Projects/InShorts/data/event/part-00003-7e210b01-29d8-430f-988f-d3e3b34da614-c000.csv")

df_interaction = pd.concat([df_interaction_1,df_interaction_2,df_interaction_3,df_interaction_4], ignore_index=True)

#preview the head data
df_interaction.head(5)

,deviceId,event_type,eventTimestamp,hashId,categoryWhenEventHappened,cardViewPosition,overallTimeSpent,searchTerm,relevancy_color,relevancy_topic,state,locality,district
0,7cb933f6-0a5b-477e-bb5d-42eb4b771970,TimeSpent-Front,1689189015000,2k4lruyx-1,My Feed,13.0,2.165,NaN,NaN,NaN,NaN,NaN,NaN
1,a1bfc2e4-c03e-4c1b-8abb-215808a89e6a,TimeSpent-Front,1689182865000,2k4lruyx-1,My Feed,17.0,3.306,NaN,NaN,NaN,NaN,NaN,NaN
2,1c53a149-303d-486e-ac62-0b9c9e469cda,TimeSpent-Front,1689180216000,2k4lruyx-1,My Feed,17.0,4.695,NaN,NaN,NaN,NaN,NaN,NaN
3,fea7a467-551c-4b64-ad48-eae0693635f3,TimeSpent-Front,1689173651000,2kk4ydgg-1,My Feed,25.0,4.238,NaN,NaN,NaN,NaN,NaN,NaN
4,1ef62ab0-e5da-4cb4-9839-49ac52f04ceb,TimeSpent-Front,1689174004000,2kk4ydgg-1,My Feed,12.0,0.931,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_interaction.shape

(3544161, 13)

In [ ]:
df_interaction.isnull().sum()

deviceId                           0
event_type                         0
eventTimestamp                     0
hashId                             7
categoryWhenEventHappened       1686
cardViewPosition                1123
overallTimeSpent                1123
searchTerm                   3543038
relevancy_color              3542849
relevancy_topic              3542849
state                        3505694
locality                     3498791
district                     3505694
dtype: int64

In [ ]:
#dropping hashid column
df_interaction = df_interaction.dropna(subset=['hashId'])

In [ ]:
df_interaction.isnull().sum()

deviceId                           0
event_type                         0
eventTimestamp                     0
hashId                             0
categoryWhenEventHappened       1686
cardViewPosition                1123
overallTimeSpent                1123
searchTerm                   3543031
relevancy_color              3542849
relevancy_topic              3542849
state                        3505687
locality                     3498784
district                     3505687
dtype: int64

In [ ]:
df_interaction["categoryWhenEventHappened"].value_counts()

categoryWhenEventHappened
My Feed        3262296
Unread          134982
All News        111595
Top Stories      14504
Trending         11916
Unknown           5945
Bookmarks         1230
Name: count, dtype: int64

In [ ]:
#setting null value to Unknown for categoryWhenEventHappened
df_interaction['categoryWhenEventHappened'] = df_interaction['categoryWhenEventHappened'].fillna('Unknown')

In [ ]:
#setting cardview position to median
df_interaction['cardViewPosition'] = pd.to_numeric(df_interaction['cardViewPosition'], errors='coerce').fillna(df_interaction['cardViewPosition'].median())

In [ ]:
#setting overallTimeSpent to 0
df_interaction['overallTimeSpent'] = pd.to_numeric(df_interaction['overallTimeSpent'], errors='coerce').fillna(0)

In [ ]:
df_interaction["searchTerm"].value_counts()

searchTerm
layoff                                        22
manipur                                       20
lay off                                       17
sack                                          16
fire                                          14
                                              ..
uttarakhand hight court judgements on rape     1
isaeli doctor                                  1
rape                                           1
naresh gatthamaneni                            1
Netflix                                        1
Name: count, Length: 771, dtype: int64

In [ ]:
df_interaction["relevancy_color"].value_counts()

relevancy_color
GREEN     554
RED       543
YELLOW    208
Name: count, dtype: int64

In [ ]:
df_interaction["relevancy_topic"].value_counts()

relevancy_topic
business                  178
national                   85
politics                   53
world                      49
sports                     35
                         ...
border-gavaskar_trophy      4
outages                     3
sri_lanka_crisis            3
delhi_pollution             3
farmers_protest             3
Name: count, Length: 97, dtype: int64

In [ ]:
#handling search term
df_interaction['searchTerm'] = (df_interaction['searchTerm'].fillna('').str.lower().str.strip())
df_interaction.loc[df_interaction['searchTerm'].str.len() < 3, 'searchTerm'] = ''

In [ ]:
#handling relevancy color
df_interaction['relevancy_color'] = (df_interaction['relevancy_color'].fillna('').str.upper().replace({'': 'UNKNOWN'}))

In [ ]:
color_map = {'GREEN': 1, 'YELLOW': 0, 'RED': -1, 'UNKNOWN': 0}
df_interaction['relevancy_score'] = df_interaction['relevancy_color'].map(color_map)

In [ ]:
#handling relevancy topic
df_interaction['relevancy_topic'] = (df_interaction['relevancy_topic'].fillna('').str.lower().str.replace('_', ' ').str.strip())

In [ ]:
#handling state, locality, district
for col in ['state', 'locality', 'district']:
    df_interaction[col] = df_interaction[col].fillna('Unknown_Location')

In [ ]:
df_interaction.isnull().sum()

deviceId                     0
event_type                   0
eventTimestamp               0
hashId                       0
categoryWhenEventHappened    0
cardViewPosition             0
overallTimeSpent             0
searchTerm                   0
relevancy_color              0
relevancy_topic              0
state                        0
locality                     0
district                     0
relevancy_score              0
dtype: int64

In [ ]:
df_interaction.to_csv('/content/drive/MyDrive/Companies Interview Projects/InShorts/cleaned_data/interaction_cleaned_data.csv',index=False)

## Test Data Cleaning

In [5]:
#loading user csv data

# Read CSV using the python engine with proper quoting
df_test_content = pd.read_csv(
    '/content/drive/MyDrive/Companies Interview Projects/InShorts/data/testing_content/part-00000-8be13c58-b74d-4e30-8877-c8b5e168035a-c000.csv',
    engine='python',        # python engine handles quotes and newlines better
    quoting=csv.QUOTE_ALL,  # treat text in quotes as one field
    quotechar='"',          # standard quote char
    escapechar='\\',        # handle escaped quotes
    on_bad_lines='warn'     # just warn for truly broken lines
)

#preview the head data
df_test_content.head(5)

,hashid,title,content,newsType,author,categories,hashtags,newsDistrict,createdAt,updatedAt,newsLanguage,sourceName
0,zdw0jrig-1,Redmi 12 5G will be a game-changer for 5G conn...,Xiaomi will debut Redmi 12 5G alongside Redmi ...,NEWS,593f9d1f81ef171ab3b63a2d,technology,NaN,NaN,2023-07-27T07:06:41.000Z,2023-07-27T07:06:41.000Z,english,Xiaomi
1,y5pfnbmp-1,Limited seats left for Hero Vired & MIT’s Prog...,Hero Group's EdTech company Hero Vired & MIT l...,NEWS,593f9d1f81ef171ab3b63a2d,education,NaN,NaN,2023-07-27T04:30:50.000Z,2023-07-27T04:30:50.000Z,english,vired.com
2,eo2eyhgk-1,Heavy to very heavy rainfall warning issued fo...,IMD has issued heavy to very heavy rainfall wa...,NEWS,5f70de9bd43821580e6d7022,national,NaN,NaN,2023-07-27T16:23:53.000Z,2023-07-27T17:12:11.285Z,english,IMD
3,fknyydal-1,Which 14 teams have qualified for 20-team T20 ...,Ireland and Scotland have qualified for the 20...,NEWS,5f70de9bd43821580e6d7022,sports,NaN,NaN,2023-07-27T14:29:59.000Z,2023-07-27T14:29:59.000Z,english,ICC
4,61ogen4w-1,42-year-old woman shot dead near her house in ...,A 42-year-old woman was shot dead near her hou...,NEWS,5f70de9bd43821580e6d7022,national,NaN,NaN,2023-07-27T17:07:31.000Z,2023-07-27T17:07:31.000Z,english,ABP

In [6]:
df_test_content.columns

Index(['hashid', 'title', 'content', 'newsType', 'author', 'categories',
       'hashtags', 'newsDistrict', 'createdAt', 'updatedAt', 'newsLanguage',
       'sourceName'],
      dtype='object')

In [7]:
df_test_content.dtypes

hashid          object
title           object
content         object
newsType        object
author          object
categories      object
hashtags        object
newsDistrict    object
createdAt       object
updatedAt       object
newsLanguage    object
sourceName      object
dtype: object

In [8]:
df_test_content.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1346 entries, 0 to 1345
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   hashid        1346 non-null   object
 1   title         1346 non-null   object
 2   content       1346 non-null   object
 3   newsType      1346 non-null   object
 4   author        1346 non-null   object
 5   categories    1346 non-null   object
 6   hashtags      95 non-null     object
 7   newsDistrict  319 non-null    object
 8   createdAt     1346 non-null   object
 9   updatedAt     1346 non-null   object
 10  newsLanguage  1346 non-null   object
 11  sourceName    1285 non-null   object
dtypes: object(12)
memory usage: 126.3+ KB

In [9]:
df_test_content.shape

(1346, 12)

In [10]:
df_test_content.describe()

,hashid,title,content,newsType,author,categories,hashtags,newsDistrict,createdAt,updatedAt,newsLanguage,sourceName
count,1346,1346,1346,1346,1346,1346,95,319,1346,1346,1346,1285
unique,1346,1210,1207,2,60,48,22,8,1204,1227,5,172
top,jqwcl4cj-1,Could've been much worse: NYC Mayor on crane c...,Six people were injured in New York City on We...,NEWS,5f70de9bd43821580e6d7022,national,NoConfidenceMotion,AP_KU,2023-07-26T10:40:53.000Z,2023-07-27T06:54:51.000Z,english,YouTube
freq,1,4,4,1285,39,467,17,94,3,3,678,193

In [11]:
df_test_content.isnull().sum()

hashid             0
title              0
content            0
newsType           0
author             0
categories         0
hashtags        1251
newsDistrict    1027
createdAt          0
updatedAt          0
newsLanguage       0
sourceName        61
dtype: int64

In [12]:
#removing the duplicates hashid
df_test_content.drop_duplicates(subset='hashid', inplace=True)

In [13]:
df_test_content['newsType'].value_counts()

newsType
NEWS          1285
VIDEO_NEWS      61
Name: count, dtype: int64

In [14]:
df_test_content['categories'].value_counts()

categories
national                            467
miscellaneous                       179
entertainment                       106
world                               104
sports                               96
politics                             87
VIDEO_NEWS                           61
politics,national                    59
business                             34
technology                           26
world,Russia-Ukraine_Conflict        16
world,national                       11
India_Tour_of_West_Indies,sports     10
sports,Ashes_2023                     9
business,national                     9
science                               8
world,business                        5
startup,technology                    5
national,technology                   5
startup                               4
business,startup                      4
world,science                         4
business,technology                   3
automobile,business                   3
sports,national                       2
entertainment,national                2
world,education                       2
politics,entertainment                2
world,entertainment                   2
science,technology                    2
startup,science,technology            2
education                             1
world,technology                      1
world,sports                          1
business,sports                       1
sports,Asian_Games_2022               1
miscellaneous,national                1
business,startup,technology           1
Wimbledon_2023,sports                 1
hatke                                 1
fashion                               1
miscellaneous,startup                 1
science,national                      1
entertainment,fashion                 1
sports,entertainment                  1
world,business,technology             1
entertainment,technology              1
politics,entertainment,national       1
Name: count, dtype: int64

In [15]:
df_test_content['hashtags'].value_counts()

hashtags
NoConfidenceMotion              17
RuckusInParliament              16
ManipurViolence                 12
GangrapesInManipur              10
Monsoons2023                    10
TwitterRenamedX                  4
BYJUSCrisis                      4
OppenheimerBhagavadGitaScene     3
OppositionAllianceINDIA          3
HarmanpreetOutburst              3
GyanvapiSurvey                   2
QuranBurningsInSweden            1
RahulDisqualifiedAsMP            1
WagnerVsRussianMilitary          1
GoFirstBankruptcy                1
MissingTitanicTourSubmarine      1
CentreDelhiOrdinance             1
Chandrayaan3Launch               1
NCPCrisis                        1
WrestlersProtest                 1
AdipurushControversy             1
ManUrinatesOnTribalLabourer      1
Name: count, dtype: int64

In [16]:
df_test_content['newsDistrict'].value_counts()

newsDistrict
AP_KU    94
UP_VA    35
KA_MY    35
MP_IN    34
BR_PA    34
UP_LU    34
GJ_VD    31
BR_GA    22
Name: count, dtype: int64

In [17]:
#setting null values to Unknown_Author
df_test_content['author'] = df_test_content['author'].fillna('Unknown_Author')

In [18]:
#setting source name to Unknown_Source
df_test_content['sourceName'] = df_test_content['sourceName'].fillna('Unknown_Source')

In [19]:
df_test_content.isnull().sum()

hashid             0
title              0
content            0
newsType           0
author             0
categories         0
hashtags        1251
newsDistrict    1027
createdAt          0
updatedAt          0
newsLanguage       0
sourceName         0
dtype: int64

In [20]:
df_test_content = df_test_content.drop(columns=['newsDistrict'])

In [21]:
df_test_content["newsLanguage"].value_counts()

newsLanguage
english     678
hindi       427
telugu       94
kannada      79
gujarati     68
Name: count, dtype: int64

In [23]:
df_test_content.isnull().sum()

hashid             0
title              0
content            0
newsType           0
author             0
categories         0
hashtags        1251
createdAt          0
updatedAt          0
newsLanguage       0
sourceName         0
dtype: int64

In [24]:
#Handling of hastag values
df_test_content['hashtags'] = df_test_content['hashtags'].fillna('')

df_test_content['hashtags'] = df_test_content['hashtags'].astype(str).str.replace('#', '', regex=False)
df_test_content['hashtags'] = df_test_content['hashtags'].str.replace(',', ' ', regex=False)
df_test_content['hashtags'] = df_test_content['hashtags'].str.replace('_', ' ', regex=False)

In [25]:
df_test_content['title'] = ( df_test_content['title'].fillna('') + ' ' + df_test_content['hashtags'].fillna(''))
df_test_content.drop(columns=['hashtags'], inplace=True)

In [26]:
df_test_content.isnull().sum()

hashid          0
title           0
content         0
newsType        0
author          0
categories      0
createdAt       0
updatedAt       0
newsLanguage    0
sourceName      0
dtype: int64

In [27]:
df_test_content.to_csv('/content/drive/MyDrive/Companies Interview Projects/InShorts/cleaned_data/test_content_cleaned_data.csv', index=False)